### PR TITLE
(maint) enable golangci-lint

### PR DESCRIPTION
**Pull request by tphoney**
part of https://github.com/overmindtech/workspace/issues/105

### CODE REVIEW

**Comment by tphoney** [comment]
@dylanratcliffe @DavidS-ovm so i have "linted" this as far as i can, I am down to  2 ambiguous test errors, https://github.com/overmindtech/sdp-go/actions/runs/10450240862/job/28934205608#step:12:83

They use a test connection that is used for similar tests that are used for tests "with no responders". However these tests looks like we do expect there to be responders. Am i incorrect for the 2 failing tests. 
Here is an example of were we expect "with no responders"
image

**Comment by DavidS-ovm** [comment]
In current `main`, the TestStart and TestAsyncCancel tests are consistently expecting no errors from `rp.Start`:

https://github.com/overmindtech/sdp-go/blob/f1df03df11e5fd3dcfe820a51b5e8511a0c4d56b/progress_test.go#L668-L671

https://github.com/overmindtech/sdp-go/blob/f1df03df11e5fd3dcfe820a51b5e8511a0c4d56b/progress_test.go#L706-L710

So whatever is impacting those tests is happening either entirely in this PR, or is an external problem independent of this PR.

**Comment by tphoney** [comment]
cheers, i will look into it

**Comment by tphoney** [comment]
@dylanratcliffe can you have a double check, just because of how much this touches

**Review by dylanratcliffe — APPROVED** [review]
Very nice

**Pull request merged**
