### PR TITLE
Renamed more things to "query"

### PR DESCRIPTION
**Pull request by dylanratcliffe**

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
No rush on this one

**Comment by DavidS-om** [comment]
I also noticed that at some point I managed to have `SnapshotStoreResult` and `SnapshotStoredResult`, which I also need to fix.

**Comment by dylanratcliffe** [comment]
@DavidS-om Did you want to do that in this PR or another one?

**Comment by DavidS-om** [comment]
rebased against current `main`

**Review by DavidS-om — APPROVED** [review]

**Pull request merged**
